name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
      APPLICATION: ${{ secrets.APPLICATION_YML }}
      SECRET: ${{ secrets.SECRET_JAVA }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Create Secret.java
      run: |
        mkdir -p ./src/main/java/com/WhatIsMethIs/config/secret
        echo "${{env.SECRET}}" > ./src/main/java/com/WhatIsMethIs/config/secret/Secret.java

    - name: Create application.yml
      run: |
        mkdir -p ./src/main/resources
        echo "${{env.APPLICATION}}" > ./src/main/resources/application.yml

    - name: Upload application.yml artifact
      uses: actions/upload-artifact@v2
      with:
        name: application.yml
        path: ./src/main/resources/application.yml

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}

    - name: Clean with Gradle  
      run: ./gradlew clean
      working-directory: ${{ env.working-directory }}

    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test
      working-directory: ${{ env.working-directory }}

    - name: Cleanup Gradle Cache
      if: always()
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties

    - name: Docker build and push
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -t ${{ secrets.PROJECT_NAME }} .
        docker tag ${{ secrets.PROJECT_NAME }} ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker rmi $(docker images -q)
          docker pull ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }} ${{ secrets.PROJECT_NAME }}
          docker stop ${{ secrets.PROJECT_NAME }} || true
          docker rm ${{ secrets.PROJECT_NAME }} || true
          docker run -d --name ${{ secrets.PROJECT_NAME }} -p 80:8080 ${{ secrets.PROJECT_NAME }}
